version: 2

models:
  - name: silver_bookings
    description: "Cleaned bookings derived from `bronze_bookings`"
    columns:
      - name: booking_id
        tests:
          - not_null
          - unique
      - name: booking_date
        tests:
          - not_null
      - name: listing_id
        tests:
          - not_null
          - relationships:
              to: ref('bronze_listings')
              field: listing_id
      - name: base_price
        tests:
          - not_null
      - name: booking_status
        tests:
          - not_null
