version: 2

models:
  - name: silver_bookings
    description: "Cleaned bookings derived from `bronze_bookings`"
    columns:
      - name: booking_id
        tests:
          - not_null
          - unique
      - name: booking_date
        tests:
          - not_null
      - name: listing_id
        tests:
          - not_null
          - relationships:
              to: ref('bronze_listings')
              field: listing_id

  - name: silver_listings_hosts
    description: "Enriched listings with host details from `bronze_listings` and `bronze_hosts`"
    columns:
      - name: listing_id
        description: "Unique identifier for the listing"
        tests:
          - not_null
          - unique
      - name: host_id
        description: "Unique identifier for the host"
        tests:
          - not_null
          - relationships:
              to: ref('bronze_hosts')
              field: host_id